// <auto-generated />
using ApiRest.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250126153135_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRest.Models.Comuna", b =>
                {
                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<int>("CodProvincia")
                        .HasColumnType("int");

                    b.Property<int>("CodComuna")
                        .HasColumnType("int");

                    b.Property<string>("NombreComuna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRegion", "CodProvincia", "CodComuna");

                    b.ToTable("Comuna");
                });

            modelBuilder.Entity("ApiRest.Models.Provincia", b =>
                {
                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<int>("CodProvincia")
                        .HasColumnType("int");

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRegion", "CodProvincia");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("ApiRest.Models.Region", b =>
                {
                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<string>("NombreRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRegion");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("ApiRest.Models.Comuna", b =>
                {
                    b.HasOne("ApiRest.Models.Provincia", "Provincia")
                        .WithMany("Comuna")
                        .HasForeignKey("CodRegion", "CodProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("ApiRest.Models.Provincia", b =>
                {
                    b.HasOne("ApiRest.Models.Region", "Region")
                        .WithMany("Provincia")
                        .HasForeignKey("CodRegion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ApiRest.Models.Provincia", b =>
                {
                    b.Navigation("Comuna");
                });

            modelBuilder.Entity("ApiRest.Models.Region", b =>
                {
                    b.Navigation("Provincia");
                });
#pragma warning restore 612, 618
        }
    }
}
