// <auto-generated />
using System;
using ApiRest.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202195034_In")]
    partial class In
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRest.Models.Boleta", b =>
                {
                    b.Property<int>("CodBoleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodBoleta"));

                    b.Property<string>("CodTransaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CorreoContacto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsInvitada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("RunCliente")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("CodBoleta");

                    b.HasIndex("CodTransaccion");

                    b.HasIndex("RunCliente");

                    b.ToTable("Boleta");
                });

            modelBuilder.Entity("ApiRest.Models.Cliente", b =>
                {
                    b.Property<int>("NumRun")
                        .HasColumnType("int");

                    b.Property<string>("A_Materno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("A_Paterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CodComuna")
                        .HasColumnType("int");

                    b.Property<int>("CodProvincia")
                        .HasColumnType("int");

                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DvRun")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("P_Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("S_Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("NumRun");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.HasIndex("CodRegion", "CodProvincia", "CodComuna");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ApiRest.Models.Comuna", b =>
                {
                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<int>("CodProvincia")
                        .HasColumnType("int");

                    b.Property<int>("CodComuna")
                        .HasColumnType("int");

                    b.Property<string>("NombreComuna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRegion", "CodProvincia", "CodComuna");

                    b.ToTable("Comuna");
                });

            modelBuilder.Entity("ApiRest.Models.DetalleBoleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CodBoleta")
                        .HasColumnType("int");

                    b.Property<int>("CodProducto")
                        .HasColumnType("int");

                    b.Property<int>("PrecioUnitario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodBoleta");

                    b.HasIndex("CodProducto");

                    b.ToTable("DetalleBoleta");
                });

            modelBuilder.Entity("ApiRest.Models.Producto", b =>
                {
                    b.Property<int>("CodProducto")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("CodProducto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ApiRest.Models.Provincia", b =>
                {
                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<int>("CodProvincia")
                        .HasColumnType("int");

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRegion", "CodProvincia");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("ApiRest.Models.Region", b =>
                {
                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<string>("NombreRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRegion");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("ApiRest.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("ApiRest.Models.Stock", b =>
                {
                    b.Property<int>("CodStock")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CodProducto")
                        .HasColumnType("int");

                    b.Property<int>("CodSucursal")
                        .HasColumnType("int");

                    b.HasKey("CodStock");

                    b.HasIndex("CodProducto");

                    b.HasIndex("CodSucursal");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("ApiRest.Models.Sucursal", b =>
                {
                    b.Property<int>("CodSucursal")
                        .HasColumnType("int");

                    b.Property<int>("CodComuna")
                        .HasColumnType("int");

                    b.Property<int>("CodProvincia")
                        .HasColumnType("int");

                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodSucursal");

                    b.HasIndex("CodRegion", "CodProvincia", "CodComuna");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("ApiRest.Models.Tarjeta", b =>
                {
                    b.Property<string>("CodTransaccion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreTransaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumTarjeta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodTransaccion");

                    b.ToTable("Tarjeta");
                });

            modelBuilder.Entity("ApiRest.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApiRest.Models.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("ApiRest.Models.Boleta", b =>
                {
                    b.HasOne("ApiRest.Models.Tarjeta", "Tarjeta")
                        .WithMany()
                        .HasForeignKey("CodTransaccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiRest.Models.Cliente", "Cliente")
                        .WithMany("Boletas")
                        .HasForeignKey("RunCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("ApiRest.Models.Cliente", b =>
                {
                    b.HasOne("ApiRest.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("CodRegion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiRest.Models.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("ApiRest.Models.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiRest.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("CodRegion", "CodProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiRest.Models.Comuna", "Comuna")
                        .WithMany()
                        .HasForeignKey("CodRegion", "CodProvincia", "CodComuna")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comuna");

                    b.Navigation("Provincia");

                    b.Navigation("Region");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiRest.Models.Comuna", b =>
                {
                    b.HasOne("ApiRest.Models.Provincia", "Provincia")
                        .WithMany("Comuna")
                        .HasForeignKey("CodRegion", "CodProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("ApiRest.Models.DetalleBoleta", b =>
                {
                    b.HasOne("ApiRest.Models.Boleta", "Boleta")
                        .WithMany("Detalles")
                        .HasForeignKey("CodBoleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiRest.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("CodProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boleta");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ApiRest.Models.Provincia", b =>
                {
                    b.HasOne("ApiRest.Models.Region", "Region")
                        .WithMany("Provincia")
                        .HasForeignKey("CodRegion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ApiRest.Models.Stock", b =>
                {
                    b.HasOne("ApiRest.Models.Producto", "Producto")
                        .WithMany("Stock")
                        .HasForeignKey("CodProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiRest.Models.Sucursal", "Sucursal")
                        .WithMany("Stock")
                        .HasForeignKey("CodSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("ApiRest.Models.Sucursal", b =>
                {
                    b.HasOne("ApiRest.Models.Comuna", "Comuna")
                        .WithMany("Sucursal")
                        .HasForeignKey("CodRegion", "CodProvincia", "CodComuna")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comuna");
                });

            modelBuilder.Entity("ApiRest.Models.UsuarioRol", b =>
                {
                    b.HasOne("ApiRest.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiRest.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiRest.Models.Boleta", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ApiRest.Models.Cliente", b =>
                {
                    b.Navigation("Boletas");
                });

            modelBuilder.Entity("ApiRest.Models.Comuna", b =>
                {
                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("ApiRest.Models.Producto", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ApiRest.Models.Provincia", b =>
                {
                    b.Navigation("Comuna");
                });

            modelBuilder.Entity("ApiRest.Models.Region", b =>
                {
                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("ApiRest.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ApiRest.Models.Sucursal", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ApiRest.Models.Usuario", b =>
                {
                    b.Navigation("Cliente")
                        .IsRequired();

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
